/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedCandidatesRouteImport } from './routes/_authenticated/candidates'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDebateRouteImport } from './routes/_authenticated/debate'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedInterviewsRouteImport } from './routes/_authenticated/interviews'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTwinRouteImport } from './routes/_authenticated/twin'
import { Route as ApiCopilotRouteImport } from './routes/api/copilot'
import { Route as ApiDebateRouteImport } from './routes/api/debate'
import { Route as AuthenticatedCandidatesCandidateIdRouteImport } from './routes/_authenticated/candidates_.$candidateId'
import { Route as AuthenticatedDebateCandidateIdRouteImport } from './routes/_authenticated/debate_.$candidateId'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs/index'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs/$jobId'
import { Route as AuthenticatedSimulatorIndexRouteImport } from './routes/_authenticated/simulator/index'
import { Route as AuthenticatedSimulatorSessionIdRouteImport } from './routes/_authenticated/simulator/$sessionId'
import { Route as AuthenticatedSimulatorNewRouteImport } from './routes/_authenticated/simulator/new'
import { Route as AuthenticatedTwinCandidateIdRouteImport } from './routes/_authenticated/twin_.$candidateId'
import { Route as AuthenticatedTwinCompareRouteImport } from './routes/_authenticated/twin_.compare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesRoute = AuthenticatedCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebateRoute = AuthenticatedDebateRouteImport.update({
  id: '/debate',
  path: '/debate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewsRoute = AuthenticatedInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTwinRoute = AuthenticatedTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebateRoute = ApiDebateRouteImport.update({
  id: '/api/debate',
  path: '/api/debate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCandidatesCandidateIdRoute =
  AuthenticatedCandidatesCandidateIdRouteImport.update({
    id: '/candidates_/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebateCandidateIdRoute =
  AuthenticatedDebateCandidateIdRouteImport.update({
    id: '/debate_/$candidateId',
    path: '/debate/$candidateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimulatorIndexRoute =
  AuthenticatedSimulatorIndexRouteImport.update({
    id: '/simulator/',
    path: '/simulator/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSimulatorSessionIdRoute =
  AuthenticatedSimulatorSessionIdRouteImport.update({
    id: '/simulator/$sessionId',
    path: '/simulator/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSimulatorNewRoute =
  AuthenticatedSimulatorNewRouteImport.update({
    id: '/simulator/new',
    path: '/simulator/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTwinCandidateIdRoute =
  AuthenticatedTwinCandidateIdRouteImport.update({
    id: '/twin_/$candidateId',
    path: '/twin/$candidateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTwinCompareRoute =
  AuthenticatedTwinCompareRouteImport.update({
    id: '/twin_/compare',
    path: '/twin/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/candidates': typeof AuthenticatedCandidatesRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debate': typeof AuthenticatedDebateRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/twin': typeof AuthenticatedTwinRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/debate': typeof ApiDebateRoute
  '/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/debate/$candidateId': typeof AuthenticatedDebateCandidateIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/simulator/$sessionId': typeof AuthenticatedSimulatorSessionIdRoute
  '/simulator/new': typeof AuthenticatedSimulatorNewRoute
  '/twin/$candidateId': typeof AuthenticatedTwinCandidateIdRoute
  '/twin/compare': typeof AuthenticatedTwinCompareRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/simulator/': typeof AuthenticatedSimulatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/candidates': typeof AuthenticatedCandidatesRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debate': typeof AuthenticatedDebateRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/twin': typeof AuthenticatedTwinRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/debate': typeof ApiDebateRoute
  '/candidates/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/debate/$candidateId': typeof AuthenticatedDebateCandidateIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/simulator/$sessionId': typeof AuthenticatedSimulatorSessionIdRoute
  '/simulator/new': typeof AuthenticatedSimulatorNewRoute
  '/twin/$candidateId': typeof AuthenticatedTwinCandidateIdRoute
  '/twin/compare': typeof AuthenticatedTwinCompareRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/simulator': typeof AuthenticatedSimulatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/candidates': typeof AuthenticatedCandidatesRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/debate': typeof AuthenticatedDebateRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/interviews': typeof AuthenticatedInterviewsRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/twin': typeof AuthenticatedTwinRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/debate': typeof ApiDebateRoute
  '/_authenticated/candidates_/$candidateId': typeof AuthenticatedCandidatesCandidateIdRoute
  '/_authenticated/debate_/$candidateId': typeof AuthenticatedDebateCandidateIdRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/simulator/$sessionId': typeof AuthenticatedSimulatorSessionIdRoute
  '/_authenticated/simulator/new': typeof AuthenticatedSimulatorNewRoute
  '/_authenticated/twin_/$candidateId': typeof AuthenticatedTwinCandidateIdRoute
  '/_authenticated/twin_/compare': typeof AuthenticatedTwinCompareRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/simulator/': typeof AuthenticatedSimulatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/audit'
    | '/candidates'
    | '/copilot'
    | '/dashboard'
    | '/debate'
    | '/emails'
    | '/interviews'
    | '/offers'
    | '/settings'
    | '/templates'
    | '/twin'
    | '/api/copilot'
    | '/api/debate'
    | '/candidates/$candidateId'
    | '/debate/$candidateId'
    | '/jobs/$jobId'
    | '/simulator/$sessionId'
    | '/simulator/new'
    | '/twin/$candidateId'
    | '/twin/compare'
    | '/jobs/'
    | '/simulator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/audit'
    | '/candidates'
    | '/copilot'
    | '/dashboard'
    | '/debate'
    | '/emails'
    | '/interviews'
    | '/offers'
    | '/settings'
    | '/templates'
    | '/twin'
    | '/api/copilot'
    | '/api/debate'
    | '/candidates/$candidateId'
    | '/debate/$candidateId'
    | '/jobs/$jobId'
    | '/simulator/$sessionId'
    | '/simulator/new'
    | '/twin/$candidateId'
    | '/twin/compare'
    | '/jobs'
    | '/simulator'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/audit'
    | '/_authenticated/candidates'
    | '/_authenticated/copilot'
    | '/_authenticated/dashboard'
    | '/_authenticated/debate'
    | '/_authenticated/emails'
    | '/_authenticated/interviews'
    | '/_authenticated/offers'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/twin'
    | '/api/copilot'
    | '/api/debate'
    | '/_authenticated/candidates_/$candidateId'
    | '/_authenticated/debate_/$candidateId'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/simulator/$sessionId'
    | '/_authenticated/simulator/new'
    | '/_authenticated/twin_/$candidateId'
    | '/_authenticated/twin_/compare'
    | '/_authenticated/jobs/'
    | '/_authenticated/simulator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  ApiDebateRoute: typeof ApiDebateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates': {
      id: '/_authenticated/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthenticatedCandidatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debate': {
      id: '/_authenticated/debate'
      path: '/debate'
      fullPath: '/debate'
      preLoaderRoute: typeof AuthenticatedDebateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews': {
      id: '/_authenticated/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/twin': {
      id: '/_authenticated/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof AuthenticatedTwinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debate': {
      id: '/api/debate'
      path: '/api/debate'
      fullPath: '/api/debate'
      preLoaderRoute: typeof ApiDebateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/candidates_/$candidateId': {
      id: '/_authenticated/candidates_/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof AuthenticatedCandidatesCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debate_/$candidateId': {
      id: '/_authenticated/debate_/$candidateId'
      path: '/debate/$candidateId'
      fullPath: '/debate/$candidateId'
      preLoaderRoute: typeof AuthenticatedDebateCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulator/': {
      id: '/_authenticated/simulator/'
      path: '/simulator'
      fullPath: '/simulator/'
      preLoaderRoute: typeof AuthenticatedSimulatorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulator/$sessionId': {
      id: '/_authenticated/simulator/$sessionId'
      path: '/simulator/$sessionId'
      fullPath: '/simulator/$sessionId'
      preLoaderRoute: typeof AuthenticatedSimulatorSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulator/new': {
      id: '/_authenticated/simulator/new'
      path: '/simulator/new'
      fullPath: '/simulator/new'
      preLoaderRoute: typeof AuthenticatedSimulatorNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/twin_/$candidateId': {
      id: '/_authenticated/twin_/$candidateId'
      path: '/twin/$candidateId'
      fullPath: '/twin/$candidateId'
      preLoaderRoute: typeof AuthenticatedTwinCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/twin_/compare': {
      id: '/_authenticated/twin_/compare'
      path: '/twin/compare'
      fullPath: '/twin/compare'
      preLoaderRoute: typeof AuthenticatedTwinCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCandidatesRoute: typeof AuthenticatedCandidatesRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDebateRoute: typeof AuthenticatedDebateRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedInterviewsRoute: typeof AuthenticatedInterviewsRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTwinRoute: typeof AuthenticatedTwinRoute
  AuthenticatedCandidatesCandidateIdRoute: typeof AuthenticatedCandidatesCandidateIdRoute
  AuthenticatedDebateCandidateIdRoute: typeof AuthenticatedDebateCandidateIdRoute
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedSimulatorSessionIdRoute: typeof AuthenticatedSimulatorSessionIdRoute
  AuthenticatedSimulatorNewRoute: typeof AuthenticatedSimulatorNewRoute
  AuthenticatedTwinCandidateIdRoute: typeof AuthenticatedTwinCandidateIdRoute
  AuthenticatedTwinCompareRoute: typeof AuthenticatedTwinCompareRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedSimulatorIndexRoute: typeof AuthenticatedSimulatorIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCandidatesRoute: AuthenticatedCandidatesRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDebateRoute: AuthenticatedDebateRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedInterviewsRoute: AuthenticatedInterviewsRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTwinRoute: AuthenticatedTwinRoute,
  AuthenticatedCandidatesCandidateIdRoute:
    AuthenticatedCandidatesCandidateIdRoute,
  AuthenticatedDebateCandidateIdRoute: AuthenticatedDebateCandidateIdRoute,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedSimulatorSessionIdRoute: AuthenticatedSimulatorSessionIdRoute,
  AuthenticatedSimulatorNewRoute: AuthenticatedSimulatorNewRoute,
  AuthenticatedTwinCandidateIdRoute: AuthenticatedTwinCandidateIdRoute,
  AuthenticatedTwinCompareRoute: AuthenticatedTwinCompareRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedSimulatorIndexRoute: AuthenticatedSimulatorIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  ApiDebateRoute: ApiDebateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
